### ISSUE TITLE
[Feature Request] Support a list of frameworks in runbenchmark.py args

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#483] opened 2022-07-31 20:40 UTC
Currently to run 3 frameworks h2oautoml, autogluon, autogluon:latest:

```
python3 runbenchmark.py h2oautoml validation 1h4c -m aws
python3 runbenchmark.py autogluon validation 1h4c -m aws
python3 runbenchmark.py autogluon:latest validation 1h4c -m aws
```

Ideally:

```
python3 runbenchmark.py [h2oautoml, autogluon, autogluon:latest] validation 1h4c -m aws
```

Benefits of the new logic is that compute can be used when using multiple instances more effectively (for example, running instances on both h2o and autogluon at the same time within the same runbenchmark.py call.

**Comment by PGijsbers** [comment] 2022-08-01 09:55
Duplicate of https://github.com/openml/automlbenchmark/issues/169

**Closed by PGijsbers** 2022-08-01 09:55 UTC
