### ISSUE TITLE
Simplify output paths

### ISSUE THREAD

**Issue by Innixma** [openml/automlbenchmark#510] opened 2023-02-20 22:29 UTC
Currently, when running AMLB on AWS mode (also happens in local mode), the output paths are longer than necessary:

This is the path saved to S3 for the `predictions.csv` output:

```
s3://bucket/autogluon.test.test.aws.20230220T221019/aws.test.test.cholesterol.0.autogluon/output/predictions/cholesterol/0/predictions.csv
```

Ideally, this could be simplified to:

```
s3://bucket/autogluon.test.test.aws.20230220T221019/aws.test.test.cholesterol.0.autogluon/output/predictions.csv
```

This is already the case for `results.csv`, which is found in:

```
s3://bucket/autogluon.test.test.aws.20230220T221019/aws.test.test.cholesterol.0.autogluon/output/results.csv
```

(Note: This applies to all frameworks, not just AutoGluon)

It would be really nice to simplify these paths so that coding logic that fetches these files is easier, since currently the path structure under `output` depends on the name of the task, which makes shell script parsing very complicated compared to if the `output` folder structure wasn't altered by the name of the task.

**Comment by PGijsbers** [comment] 2024-12-09 18:48
Duplicate of #647. While this issue was created first, the other has more info so I close this.

**Closed by PGijsbers** 2024-12-09 18:48 UTC
