### ISSUE TITLE
503 Error when downloading dataset

### ISSUE THREAD

**Issue by eddiebergman** [openml/automlbenchmark#573] opened 2023-07-21 13:40 UTC
I'm getting an issue with 503 errors from the openml servers when using the pinned requirement of `0.13.1`, where it can't download the tasks from openml

**Comment by eddiebergman** [comment] 2023-07-21 13:59
Forcing an update to `0.14.1` doesn't work either due to renamed variables.

**Comment by PGijsbers** [comment] 2023-07-22 08:32
OpenML is experiencing some server issues, and while they last `openml==0.13.1` will not be able to download new datasets. I applied a patch to the benchmark (#579) that makes the benchmark compatible with newer versions of openml which can download data despite the server issues. This makes openml fall back on loading arff files, which in some cases are different and thus **may lead to different results**. Be deliberate about whether upgrading or waiting is the right choice for you! If you do decide to upgrade simply update your openml python installation: `python -m pip install --upgrade openml`. You should now be able to run the benchmark again on new datasets.

**Comment by suzhoum** [comment] 2023-07-25 17:28
Thanks for working on the fix! I'm currently testing on the merged fix, on both my dev machine and in docker container that I built that's dependent on AMLB. It works fine with on my dev machine, but when running in docker container, I encountered a series of git errors after the benchmark run has started, which I didn't see before. Is there anything that might have led to the error?

```
Running benchmark `AutoGluon:stable` on `small` framework in `local` mode.
Loading frameworks definitions from ['/app/ag_bench_runs/tabular/ag_bench_test/automlbenchmark/resources/frameworks.yaml'].
Loading benchmark constraint definitions from ['/app/ag_bench_runs/tabular/ag_bench_test/automlbenchmark/resources/constraints.yaml'].
Loading benchmark definitions from /app/ag_bench_runs/tabular/ag_bench_test/automlbenchmark/resources/benchmarks/small.yaml.
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by PGijsbers** [comment] 2023-07-25 18:33
Does the script stop after that? If not, then I think this is expected behaviour (though something we might want to change):
when building the docker image [files are copied](https://github.com/openml/automlbenchmark/blob/76edcf3ad7e97ce4af6e4cad73c66f8f79ed5b4d/amlb/runners/docker.py#L161C2-L161C2) into the image. The `.git` files are not copied into the repository. This means that the version of the benchmark that exists in a container  is not a git repository. When the benchmark is running inside docker it runs as if it is doing a local run, so it tries to record any information about the git environment - in this case it can't fine any and reports that. In the end, the git information of the data present on the host machine should be recorded for the experiment.
If this deviates from the behaviour you observe, then it is likely a bug and I would appreciate it if you open a new issue (but unlikely to be introduced by the changes for `openml-python 0.14.1` compatibility).

**Comment by suzhoum** [comment] 2023-07-25 20:40
I opened a new issue https://github.com/openml/automlbenchmark/issues/580 since I believe it's not related to this one after investigation.

**Comment by PGijsbers** [comment] 2023-07-30 14:31
Closing this issue all files should be available again on the server. Feel free to re-open if you find a dataset that wasn't recovered correctly (or, even better, open an issue on https://github.com/openml/openml-data).

**Closed by PGijsbers** 2023-07-30 14:31 UTC
Labels: Answered, openml
